/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

export default function Model() {
  const group = useRef();
  const { nodes, materials } = useGLTF('/brain-centered.glb');
  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="node_id34"
          position={[1.25, 0.76, 0.72]}
          rotation={[-1.67, -0.29, -1.84]}
          scale={[0, 0, 0]}
        />
        <group
          name="Light001"
          position={[4.08, 5.9, -1.01]}
          rotation={[1.89, 0.88, -2.05]}
        />
        <group
          name="Camera001"
          position={[7.36, 4.96, 6.93]}
          rotation={[1.24, 0.33, -0.76]}
        />
        <group name="root" position={[-0.07, -0.04, -0.4]}>
          <group
            name="node_id34001"
            position={[0.51, 0.39, 1.47]}
            rotation={[-2.79, -0.93, -2.71]}
            scale={[0, 0, 0]}
          >
            <mesh
              name="mesh_id32001"
              geometry={nodes.mesh_id32001.geometry}
              material={materials['84.001']}
              position={[-581.34, -498.2, 826.7]}
              rotation={[0.69, 0.5, -0.34]}
              scale={[118.38, 118.38, 118.38]}
            />
            <mesh
              name="mesh_id33001"
              geometry={nodes.mesh_id33001.geometry}
              material={materials['86.001']}
              position={[-789.64, -492.11, 965.45]}
              rotation={[0.65, 0.5, -0.41]}
              scale={[118.38, 118.38, 118.38]}
            />
          </group>
        </group>
        <group
          name="Light"
          position={[4.08, 5.9, -1.01]}
          rotation={[1.89, 0.88, -2.05]}
        />
        <group
          name="Camera"
          position={[7.36, 4.96, 6.93]}
          rotation={[1.24, 0.33, -0.76]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/brain-centered.glb');
