/* eslint-disable prettier/prettier */
/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable @typescript-eslint/ban-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { a, useSpring } from '@react-spring/three';

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_0_1: THREE.Mesh;
    mesh_0_2: THREE.Mesh;
    mesh_0_3: THREE.Mesh;
    mesh_0_4: THREE.Mesh;
    mesh_0_5: THREE.Mesh;
    mesh_0_6: THREE.Mesh;
    mesh_0_7: THREE.Mesh;
    mesh_0_8: THREE.Mesh;
    mesh_0_9: THREE.Mesh;
    mesh_0_10: THREE.Mesh;
    mesh_0_11: THREE.Mesh;
    mesh_0_12: THREE.Mesh;
    mesh_0_13: THREE.Mesh;
    mesh_0_14: THREE.Mesh;
    mesh_0_15: THREE.Mesh;
    mesh_0_16: THREE.Mesh;
    mesh_0_17: THREE.Mesh;
    mesh_0_18: THREE.Mesh;
    mesh_0_19: THREE.Mesh;
    mesh_0_20: THREE.Mesh;
    mesh_0_21: THREE.Mesh;
    mesh_0_22: THREE.Mesh;
    mesh_0_23: THREE.Mesh;
    mesh_0_24: THREE.Mesh;
    mesh_0_25: THREE.Mesh;
    mesh_0_26: THREE.Mesh;
    mesh_0_27: THREE.Mesh;
    mesh_0_28: THREE.Mesh;
    mesh_0_29: THREE.Mesh;
    mesh_0_30: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials }: any = useGLTF(
    `${__dirname.substring(
      0,
      __dirname.length - 4
    )}/assets/models/spineless.glb`
  ) as GLTFResult;

  const [mat] = useState(
    new THREE.MeshLambertMaterial({
      color: '#333382',
      transparent: true,
      opacity: 0.5,
    })
  );

  const [hover, setHover] = useState(false)

  useSpring({
    color : hover ? 'white' : 'red',
    onChange: ({ color } : any) => materials[""].color.set(color)

 })

  mat.color.set('#333382');
  return (
   // <a.group ref={group} onPointerOver={() => setHover(true)} onPointerOut={() => setHover(false)} dispose={null}>
      <group name="Asset3DLoadersceneRoot" scale={[0.5, 0.5, 0.5]}>
        <ambientLight />
        <mesh geometry={nodes.mesh_0.geometry}>
          <meshLambertMaterial
            color="#6f4f1d"
            transparent
            opacity={0.8}
          />
        </mesh>

        <mesh geometry={nodes.mesh_0_1.geometry} material={mat}>
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_2"
          geometry={nodes.mesh_0_2.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_3"
          geometry={nodes.mesh_0_3.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_4"
          geometry={nodes.mesh_0_4.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_5"
          geometry={nodes.mesh_0_5.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_6"
          geometry={nodes.mesh_0_6.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_7"
          geometry={nodes.mesh_0_7.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_8"
          geometry={nodes.mesh_0_8.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_9"
          geometry={nodes.mesh_0_9.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_10"
          geometry={nodes.mesh_0_10.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_11"
          geometry={nodes.mesh_0_11.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_12"
          geometry={nodes.mesh_0_12.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_13"
          geometry={nodes.mesh_0_13.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_14"
          geometry={nodes.mesh_0_14.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_15"
          geometry={nodes.mesh_0_15.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_16"
          geometry={nodes.mesh_0_16.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_17"
          geometry={nodes.mesh_0_17.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_18"
          geometry={nodes.mesh_0_18.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_19"
          geometry={nodes.mesh_0_19.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_20"
          geometry={nodes.mesh_0_20.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_21"
          geometry={nodes.mesh_0_21.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_22"
          geometry={nodes.mesh_0_22.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_23"
          geometry={nodes.mesh_0_23.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_24"
          geometry={nodes.mesh_0_24.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_25"
          geometry={nodes.mesh_0_25.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_26"
          geometry={nodes.mesh_0_26.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_27"
          geometry={nodes.mesh_0_27.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_28"
          geometry={nodes.mesh_0_28.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_29"
          geometry={nodes.mesh_0_29.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>

        <mesh
          name="mesh_0_30"
          geometry={nodes.mesh_0_30.geometry}
          material={mat}
        >
          {/* <meshStandardMaterial color="white" transparent opacity={0.8} /> */}
        </mesh>
      </group>
  //  </a.group>
  );
}

useGLTF.preload(
  `${__dirname.substring(0, __dirname.length - 4)}/assets/models/spineless.glb`
);
